### ISSUE TITLE
Biovalidator Throws 504 Error when accessions field is included in payload

### ISSUE THREAD

**Issue by KociOrges** [ebi-ait/checklist#167]
The Biovalidator service is throwing a 504 Gateway Timeout error when the `accessions` field is included in the payload for validation, e.g., `"accessions": ["SAMEA2397676"]`. The issue appears to be related to the asynchronous validation performed by the `isValidIdentifier` keyword for `accessions`.

After some investigation with Isuru, we found that this issue does not occur when running on localhost, suggesting it might be related to the Kubernetes environment.

The impact is on json schemas that use the identifiers.org schema keyword. It does not impact ENA checklists.

This is a biovalidator issue rather than an ENA checklist Editor issue.

**Comment by theisuru** [comment]
It seems K8s can't access outside world. Need to contact support and ask if we can open connection to identifier.org

**Comment by amnonkhen** [comment]
see #180 
Will be solved when moving to HL k8s

**Comment by theisuru** [comment]
HTTP_PROXY configured in container spec as env variable in the k8s Deployment configuration.
```yaml
          env:
            - name: HTTP_PROXY
              value: $HTTP_PROXY
            - name: HTTPS_PROXY
              value: $HTTP_PROXY
            - name: NO_PROXY
              value: $NO_PROXY
            - name: http_proxy
              value: $HTTP_PROXY
            - name: https_proxy
              value: $HTTP_PROXY
            - name: no_proxy
              value: $NO_PROXY
```
