### ISSUE TITLE
API testing for schema store

### ISSUE THREAD

**Issue by theisuru** [ebi-ait/checklist#174]
- [ ] k8s liveness probes for all services
   - checklist editor
   - schema store
   - biovalidator  
- [x] create a postman collection for different user scenarios each one in a separate folder
- [ ] run after deployment in gitlab
   - use newman to call postman from CL

**Comment by theisuru** [comment]
Postman collection is completed and is in [api-test](https://github.com/EBIBioSamples/json-schema-store/tree/dev/src/api-test) directory of json-schema-store. 

todo: Decide how we want to integrate this with CICD

**Comment by Wkt8** [comment]
Check with amnon the requirement of the liveness probes

**Comment by amnonkhen** [comment]
The liveness probes should see whether the app is running.
 - Spring boot: it should be the built in health check resource: `/actuator/health`: e.g. [on wwwint](https://wwwint.ebi.ac.uk/biosamples/schema-store/actuator/health)
 - react admin - the root page '/', e.g. [on wwwint](https://wwwint.ebi.ac.uk/biosamples/checklist-editor)
 - for biovalidator - consult @theisuru

**Comment by amnonkhen** [comment]
Here is an example for execution of postman from gitlab:

```yaml
postman-tests:
  stage: test
  image: postman/newman
  script:
    - echo "Running Postman tests"
    - newman run postman-collection.json --environment postman-environment.json --env-var base_url=$BASE_URL
  only:
    - main
  dependencies:
    - deploy
```

replace `base_url=$BASE_URL` with the name of the postman variable for the schema store and the Gitlab variable that contains its address.
