### ISSUE TITLE
fix access to identifiers.org from hx cluster

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#180]

**Comment by Wkt8** [comment]
This is part of #171

**Comment by theisuru** [comment]
HTTP_PROXY configured in container spec as env variable.
```
          env:
            - name: HTTP_PROXY
              value: $HTTP_PROXY
            - name: HTTPS_PROXY
              value: $HTTP_PROXY
            - name: NO_PROXY
              value: $NO_PROXY
            - name: http_proxy
              value: $HTTP_PROXY
            - name: https_proxy
              value: $HTTP_PROXY
            - name: no_proxy
              value: $NO_PROXY
```
